git rm -rf --cached .
git add joesTriac.aps
git add joestriac.aws
git add *.h
git add *.c
git add *.atsln
git add *.cproj
git add gitAddFiles.bat
git add gitAddFiles.sh
git add checkOriginMaster.sh
git add checkOriginMaster.bat
git add default/joesTriac.hex
git add ATtinyJT/ATtinyJT.aps
git add   ATtinyJT/ATtinyJT.c
git add   joesTriac.c
git add ATtinyJT/USI_TWI_Slave.c
git add ATtinyJT/attinyjt.aws
git add ATtinyJT/USI_TWI_Slave.h
git add JTWebPages
git add JTWebPages/rustlight/
git add JTWebPages/apply/DSCF5661-c3.jpg
git add rational/
git add	ATtinyJT/ATtinyJT.atsln
git add ATtinyJT/ATtinyJT.cproj
git add ATtinyJT/*
git add eagle/*
git add ATmega644p/*
git add stm32/jt/
git add stm32/.gitignore
git add stm32/jt/.gitignore
git add stm32/jt/TouchGFX/.gitignore
git status