git add joesTriac.aps
git add joestriac.aws
git add *.h
git add *.c
git add *.atsln
git add *.cproj
git add gitAddFiles.bat
git add default/joesTriac.hex
git add ATtinyJT/ATtinyJT.aps
git add   ATtinyJT/ATtinyJT.c
git add   joesTriac.c
git add ATtinyJT/USI_TWI_Slave.c
git add ATtinyJT/attinyjt.aws
git add ATtinyJT/USI_TWI_Slave.h
git add JTWebPages
git add JTWebPages/rustlight/
git add JTWebPages/apply/DSCF5661-c3.jpg
git add  joesTriac.mdl
git add	ATtinyJT/ATtinyJT.atsln
git add ATtinyJT/ATtinyJT.cproj
git add ATmega644p/*
git add rational/*
git add gitAddFiles.sh
git add checkOriginMaster.sh
git add checkOriginMaster.bat
git add stm32/*
git add stm32/.gitignore
git status